"""Add review models

Revision ID: 17a2eec748f8
Revises: 
Create Date: 2026-07-04 02:37:38.911494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '17a2eec748f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
