"""Add title and is_archived to chat_sessions

Revision ID: b30679180ef9
Revises: 18a3ffd849e9
Create Date: 2026-07-05 01:35:29.818263
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = 'b30679180ef9'
down_revision: Union[str, None] = '18a3ffd849e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_patient_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state', sqlite.JSON(), nullable=False),
    sa.Column('metadata_info', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=1)
    op.create_index(op.f('ix_chat_sessions_patient_id'), 'chat_sessions', ['patient_id'], unique=False)
    # ### end Alembic commands ###
